# build : docker buildx build -f deploy/Dockerfile -t flea .

FROM node:20.5-alpine AS BASEIMAGE

WORKDIR /src
COPY package*.json ./
RUN npm ci
COPY . .
RUN nest build
# RUN npm run prebuild && npm run build && npm prune --production

FROM node:20.5-alpine

WORKDIR /src
ENV TZ=Asia/Tokyo
COPY --from=BASEIMAGE /dist /src/dist
COPY --from=BASEIMAGE /node_modules /src/node_modules
EXPOSE 3001

CMD ["node", "dist/src/main.js"]